# Generated by Django 5.0.7 on 2024-07-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HydroProjectForm',
            new_name='HydroProject',
        ),
    ]
