# Generated by Django 5.0.7 on 2024-07-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_hydroprojectform_hydroproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydroproject',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
