# Generated by Django 5.0.7 on 2024-07-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_hydroproject_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HydroProject',
            new_name='Sheet1',
        ),
    ]
